### ISSUE TITLE
Function doesn't work

### ISSUE THREAD

**Issue by 945307242** [spookynova/IL2CppAndroid#1]

**Comment by seedhollow** [comment]
Can you tell me more about the issue? I appreciate it if you showed me the details of this issue so that I could check it

**Comment by qq1433161035** [comment]
"It indeed doesn't work, whether using Hooking or ESP. After I changed it to Dobby, Hooking became effective, but ESP is still ineffective; it can only draw text on the screen and cannot draw ESP lines for the player."

**Comment by qq1433161035** [comment]
> Can you tell me more about the issue? I appreciate it if you showed me the details of this issue so that I could check it

"It indeed doesn't work, whether using Hooking or ESP. After I changed it to Dobby, Hooking became effective, but ESP is still ineffective; it can only draw text on the screen and cannot draw ESP lines for the player."

**Comment by seedhollow** [comment]
I've already checked it and made some progress. The ESP Line is working, and I’ve reworked the hooking method. I’ll include it in the next update.

![Screenshot_20241220-163035](https://github.com/user-attachments/assets/d10dcb10-02af-43f4-99b4-56fed440a896)

**Comment by seedhollow** [comment]
You can try new method like this on `hook_thread` method

```cpp
IL2CPP::Hook("WarPolygon.CPlayerLocal", "get_CurrentHeight", 0, (void*) HookPlayerCurrentHeight, (void**)&old_PlayerCurrentHeight);
```
